# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "active_scaffold_batch"
  s.version = "3.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Volker Hochstein"]
  s.date = "2012-01-12"
  s.description = "You want to destroy/update many records at once with activescaffold?"
  s.email = "activescaffold@googlegroups.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README"
  ]
  s.files = [
    ".document",
    "LICENSE.txt",
    "README",
    "Rakefile",
    "active_scaffold_batch.gemspec",
    "frontends/default/views/_batch_create_form.html.erb",
    "frontends/default/views/_batch_create_form_attribute.html.erb",
    "frontends/default/views/_batch_create_form_body.html.erb",
    "frontends/default/views/_batch_update_form.html.erb",
    "frontends/default/views/_batch_update_form_attribute.html.erb",
    "frontends/default/views/_batch_update_form_attribute_scope.html.erb",
    "frontends/default/views/_batch_update_form_body.html.erb",
    "frontends/default/views/batch_create.html.erb",
    "frontends/default/views/batch_update.html.erb",
    "frontends/default/views/on_batch_base.js.erb",
    "frontends/default/views/on_batch_create.js.erb",
    "frontends/default/views/on_batch_update.js.erb",
    "init.rb",
    "lib/active_scaffold/actions/batch_base.rb",
    "lib/active_scaffold/actions/batch_create.rb",
    "lib/active_scaffold/actions/batch_destroy.rb",
    "lib/active_scaffold/actions/batch_update.rb",
    "lib/active_scaffold/config/batch_base.rb",
    "lib/active_scaffold/config/batch_create.rb",
    "lib/active_scaffold/config/batch_destroy.rb",
    "lib/active_scaffold/config/batch_update.rb",
    "lib/active_scaffold/helpers/batch_create_column_helpers.rb",
    "lib/active_scaffold/helpers/calendar_date_select_update_column_helpers.rb",
    "lib/active_scaffold/helpers/datepicker_update_column_helpers.rb",
    "lib/active_scaffold/helpers/update_column_helpers.rb",
    "lib/active_scaffold_batch.rb",
    "lib/active_scaffold_batch/config/core.rb",
    "lib/active_scaffold_batch/locale/de.yml",
    "lib/active_scaffold_batch/locale/en.yml",
    "lib/active_scaffold_batch/version.rb",
    "uninstall.rb"
  ]
  s.homepage = "http://github.com/vhochstein/active_scaffold_batch"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Batch Processing for ActiveScaffold"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

